# Generated by Django 5.2.10 on 2026-07-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0004_numerotelefonico_valor_mensual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numerotelefonico',
            name='valor_mensual',
            field=models.FloatField(db_default=0.0, default=0.0),
        ),
    ]
